# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-18 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0002_auto_20191018_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instagram_photos/'),
        ),
    ]
