# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-24 10:29
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0010_auto_20191023_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=tinymce.models.HTMLField(),
        ),
    ]
