# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-25 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0011_auto_20191024_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.TextField(blank=True),
        ),
    ]
